# Repository Information
name: Cyrus's APP Repository
identifier: xm798.feathernest
iconURL: https://github.com/Xm798/FeatherNest/blob/master/assets/icon@4x.png?raw=true
website: https://github.com/Xm798/FeatherNest
